name: ci_test

on: [push]

jobs:
  main:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache things
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}
        path: |
          ~/.cache
          ~/.poetry
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        curl -sSL https://install.python-poetry.org | python3 -
        export POETRY_HOME=$HOME/.poetry/bin
        echo "$POETRY_HOME" >>$GITHUB_PATH
        export PATH="$POETRY_HOME:$PATH"
        poetry install
    - name: Run pre-commit
      run: |
        pre-commit run -av
    # - name: Verify executables run
    #   run: |
    #     poetry run tests/test_executable_help.py
    # - name: Run Pytest
    #   run: |
    #     poetry run pytest -vv

